"""create users table

Revision ID: 969d68c56ebf
Revises: bc1b0438b84b
Create Date: 2025-11-18 11:48:13.114826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '969d68c56ebf'
down_revision: Union[str, Sequence[str], None] = 'bc1b0438b84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('betas', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('betas', 'updated_at')
    # ### end Alembic commands ###
