"""create users table

Revision ID: ddf1234edce3
Revises: 1e3019174b0d
Create Date: 2025-12-01 13:05:17.715384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf1234edce3'
down_revision: Union[str, Sequence[str], None] = '1e3019174b0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('betas', 'uptaded_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('betas', sa.Column('uptaded_at', sa.DATETIME(), nullable=False))
    # ### end Alembic commands ###
