"""create users table

Revision ID: ec3d17953350
Revises: 969d68c56ebf
Create Date: 2025-12-01 12:57:23.284229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec3d17953350'
down_revision: Union[str, Sequence[str], None] = '969d68c56ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('betas', sa.Column('uptaded_at', sa.DateTime(), nullable=False))
    op.drop_column('betas', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('betas', sa.Column('updated_at', sa.DATETIME(), nullable=False))
    op.drop_column('betas', 'uptaded_at')
    # ### end Alembic commands ###
